// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(
  "com.fasterxml.jackson.core" % "jackson-annotations" % "2.9.8",
  "com.fasterxml.jackson.core" % "jackson-core" % "2.9.8",
  "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.8",
  "com.lowagie" % "itext" % "2.1.7.js6",
  "commons-beanutils" % "commons-beanutils" % "1.9.3",
  "commons-collections" % "commons-collections" % "3.2.2",
  "commons-digester" % "commons-digester" % "2.1",
  "commons-logging" % "commons-logging" % "1.1.1",
  "javax.inject" % "javax.inject" % "1",
  "net.java.dev.jna" % "jna" % "5.2.0",
  "net.java.dev.jna" % "jna-platform" % "5.2.0",
  "net.sf.jasperreports" % "jasperreports" % "6.9.0",
  "org.apache.commons" % "commons-collections4" % "4.2",
  "org.apache.commons" % "commons-lang3" % "3.4",
  "org.bouncycastle" % "bcprov-jdk15on" % "1.52",
  "org.codehaus.castor" % "castor-core" % "1.4.1",
  "org.codehaus.castor" % "castor-xml" % "1.4.1",
  "org.eclipse.jdt.core.compiler" % "ecj" % "4.4.2",
  "org.jfree" % "jcommon" % "1.0.23",
  "org.jfree" % "jfreechart" % "1.0.19"
)
// LIBRARY_DEPENDENCIES_HASH 5dd670f30ce85cd8e62c5dc91859390aa5e164c3
